AWSTemplateFormatVersion: '2010-09-09'
Description: CFN template para crear  Bucket Artifacts

Parameters:

  Ambiente:
    Description: Ambiente de despliegue
    Type: String
    AllowedValues:
      - "prod"
      - "develop"   
  Project:
    Type: String
    Description: Nombre del Proyecto
  S3KMSArn:
    Type: String
    Description: KMS Key ID para Buckets S3      

Resources:

  S3BucketArtifacts:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub koandina-forecast-artifacts-${Ambiente}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref S3KMSArn
      Tags:
        - Key: Name
          Value:  !Sub "${Project}-cl-${Ambiente}-S3"
        - Key: Ambiente de despliegue
          Value: !Ref Ambiente
        - Key: ResourceType
          Value: Bucket
        - Key: Partner
          Value: Arkho
        - Key: Project
          Value: !Ref Project 

  S3BucketSignedURL:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub koandina-forecast-signedurl-${Ambiente}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref S3KMSArn
      Tags:
        - Key: Name
          Value:  !Sub "${Project}-cl-${Ambiente}-S3"
        - Key: Ambiente de despliegue
          Value: !Ref Ambiente
        - Key: ResourceType
          Value: Bucket
        - Key: Partner
          Value: Arkho
        - Key: Project
          Value: !Ref Project 

Outputs:
  BucketSignedURL:
    Description: Bucket Signed URL
    Value: !Ref S3BucketSignedURL

  BucketArtifacts:
    Description: Bucket Artifacts
    Value: !Ref S3BucketArtifacts