AWSTemplateFormatVersion: '2010-09-09'
Description: CFN template para crear  Bucket Artifacts

Parameters:

  Ambiente:
    Description: Ambiente de despliegue
    Type: String
    AllowedValues:
      - "prod"
      - "develop"   
  Project:
    Type: String
    Description: Nombre del Proyecto
  S3KMSArn:
    Type: String
    Description: KMS Key ID para Buckets S3      

Resources:

  S3BucketArtifacts:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${Project}-Artifacts-${Ambiente}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref S3KMSArn
      Tags:
        - Key: Name
          Value:  !Sub "koandina-${Project}-cl-${Ambiente}-S3"
        - Key: Ambiente de despliegue
          Value: !Ref Ambiente
        - Key: ResourceType
          Value: Bucket
        - Key: Partner
          Value: Arkho
        - Key: Project
          Value: !Ref Project 

  S3BucketSignedURL:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${Project}-SignedURL-${Ambiente}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref S3KMSArn
      Tags:
        - Key: Name
          Value:  !Sub "koandina-${Project}-cl-${Ambiente}-S3"
        - Key: Ambiente de despliegue
          Value: !Ref Ambiente
        - Key: ResourceType
          Value: Bucket
        - Key: Partner
          Value: Arkho
        - Key: Project
          Value: !Ref Project 

  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3BucketArtifacts
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: s3:*
            Effect: Deny
            Resource:
            - !Sub 'arn:aws:s3:::${S3BucketArtifacts}'
            - !Sub 'arn:aws:s3:::${S3BucketArtifacts}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Principal: "*"      

  SignedURLBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3BucketSignedURL
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: s3:*
            Effect: Deny
            Resource:
            - !Sub 'arn:aws:s3:::${S3BucketSignedURL}'
            - !Sub 'arn:aws:s3:::${S3BucketSignedURL}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Principal: "*"      
            