AWSTemplateFormatVersion: 2010-09-09
Description: Root stack for RDS and RDS Proxy stacks

Parameters:
  NombreAplicacion:
    Description: Nombre de la aplicacion
    Type: String
  DBMasterUserPassword:
    Description: Contraseña de la base de datos
    Type: String
  DBMasterUsername:
    Description: Nombre de usuario master/superuser.
    Type: String
  Ambiente:
    Description: Ambiente
    Type: String
  SubnetId2 :
    Description: Subnet id 
    Type: String
  AllowedCIDRVPC:
    Description: VPC
    Type: String
  SubnetId1:
    Description: Subnet id 
    Type: String
  VpcId:
    Description: VPC id 
    Type: String
  AllowedCIDRBR:
    Description: CIDR para Brasil
    Type: String
  DBName:
    Description: Nombre de la BD
    Type: String
  AllowedCIDRCL:
    Description: CIDR para Chile
    Type: String
  ProxyName:
    Description: Nombre del Proxy
    Type: String
  SubnetIds:
    Description: Subnets para el proxy 
    Type: String        

Resources:

  NestedStackDB:
    Type: AWS::CloudFormation::Stack     
    Properties:  
      Parameters:
        Ambiente: !Ref Ambiente
        SubnetId2: !Ref SubnetId2
        VpcId: !Ref VpcId
        SubnetId1: !Ref SubnetId1
        NombreAplicacion: !Ref NombreAplicacion
        DBMasterUsername: !Ref DBMasterUsername
        AllowedCIDRVPC: !Ref AllowedCIDRVPC
        VpcId: !Ref VpcId
        AllowedCIDRBR: !Ref AllowedCIDRBR
        DBName: !Ref DBName
        AllowedCIDRCL: !Ref AllowedCIDRCL
      TemplateURL: https://koandina-deployment.s3.amazonaws.com/deployment-rds.yaml 

  NestedStackProxy:  
    Type: AWS::CloudFormation::Stack    
    DependsOn: NestedStackDB
    Properties:
      TemplateURL: https://koandina-deployment.s3.amazonaws.com/deployment-rds-proxy.yaml     
      Parameters:        
        Ambiente: !Ref Ambiente
        SubnetId2: !Ref SubnetId2
        VpcId: !Ref VpcId
        SubnetId1: !Ref SubnetId1
        SubnetIds: !Ref SubnetIds
        VpcId: !Ref VpcId
        ProxyName: !Ref ProxyName
        ProxySecretArn:  
          Fn::GetAtt: [NestedStackDB,Outputs.ProxySecretArn]        
