AWSTemplateFormatVersion: 2010-09-09
Description: Root stack for RDS and RDS Proxy stacks

Parameters:
  NombreAplicacion:
    Description: Nombre de la aplicacion
    Type: String
  DBMasterUsername:
    Description: Nombre de usuario master/superuser.
    Type: String
  Ambiente:
    Description: Ambiente
    Type: String
  SubnetId2 :
    Description: Subnet id 
    Type: String
  AllowedCIDRVPC:
    Description: VPC
    Type: String
  SubnetId1:
    Description: Subnet id 
    Type: String
  VpcId:
    Description: VPC id 
    Type: String
  AllowedCIDRBR:
    Description: CIDR para Brasil
    Type: String
  DBName:
    Description: Nombre de la BD
    Type: String
  AllowedCIDRCL:
    Description: CIDR para Chile
    Type: String
  ProxyName:
    Description: Nombre del Proxy
    Type: String
  Project:
    Description: Nombre del Proyecto
    Type: String  


Resources:

  NestedStackSecrets:
    Type: AWS::CloudFormation::Stack     
    DeletionPolicy: Retain       
    Properties:  
      TemplateURL: https://koandina-deployment.s3.amazonaws.com/deployment-secret.yaml    
      Parameters:
        Ambiente: !Ref Ambiente
        DBMasterUsername: !Ref DBMasterUsername
        Project: !Ref Project

  # NestedStackDB:
  #   Type: AWS::CloudFormation::Stack     
  #   DeletionPolicy: Retain       
  #   Properties:  
  #     Parameters:
  #       Ambiente: !Ref Ambiente
  #       SubnetId2: !Ref SubnetId2
  #       VpcId: !Ref VpcId
  #       SubnetId1: !Ref SubnetId1
  #       NombreAplicacion: !Ref NombreAplicacion
  #       DBMasterUsername: !Ref DBMasterUsername
  #       AllowedCIDRVPC: !Ref AllowedCIDRVPC
  #       VpcId: !Ref VpcId
  #       AllowedCIDRBR: !Ref AllowedCIDRBR
  #       DBName: !Ref DBName
  #       AllowedCIDRCL: !Ref AllowedCIDRCL
  #     TemplateURL: https://koandina-deployment.s3.amazonaws.com/deployment-rds.yaml

  # NestedStackProxy:  
  #   Type: AWS::CloudFormation::Stack    
  #   DependsOn: NestedStackDB
  #   Properties:
  #     TemplateURL: https://koandina-deployment.s3.amazonaws.com/deployment-rds-proxy.yaml
  #     Parameters:        
  #       Ambiente: !Ref Ambiente
  #       SubnetId2: !Ref SubnetId2
  #       VpcId: !Ref VpcId
  #       SubnetId1: !Ref SubnetId1
  #       ProxyName: !Ref ProxyName
  #       AllowedCIDRBR: !Ref AllowedCIDRBR
  #       AllowedCIDRCL: !Ref AllowedCIDRCL        
  #       DBName: !Ref DBName        
  #       ProxySecretArn:
  #         Fn::GetAtt:
  #           - NestedStackDB
  #           - Outputs.SecretDB          