AWSTemplateFormatVersion: '2010-09-09'
Description:  Template for Cognito Federated User Pool.

Parameters:
  Environment:
    Type: String
    Description: Environment Name
    AllowedValues:
      - "prod"
      - "develop"    
    Default: develop
  CognitoUserPoolName:
    Type: String
    Default: KoandinaUserPool
  CognitoUserPoolClientName:
    Type: String
    Default: KoandinaPoolClient
  KoandinaProviderName:
    Type: String
    Default: "AzureAD"
  KoandinaMetadataURL:
    Type: String
    Default: "https://login.microsoftonline.com/864b6239-952e-4d13-adaa-06e01f3364a7/federationmetadata/2007-06/federationmetadata.xml?appid=7c71c1ea-be16-44ca-9491-64d41549ce9e"  
  CallbackURLs:
    Type: String
    Default: "http://localhost:3000/login/"
  LogoutURLs:
    Type: String
    Default: "http://localhost:3000/dashboard/"


Resources:
  KoandinaUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Ref: CognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email   
          Mutable: true 
  
  UserAzurePoolIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref KoandinaUserPool
      ProviderName: !Ref KoandinaProviderName
      ProviderType: SAML
      ProviderDetails:
        MetadataURL: !Ref KoandinaMetadataURL
      AttributeMapping:
        email: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
        name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"   
        family_name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"             
        given_name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"

  KoandinaUserPoolClient:
    DependsOn: UserAzurePoolIdentityProvider
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - profile
      SupportedIdentityProviders: 
        - !Ref KoandinaProviderName
      CallbackURLs: 
        - !Ref CallbackURLs
      LogoutURLs: 
        - !Ref LogoutURLs
      UserPoolId:
        Ref: KoandinaUserPool
      ClientName:
        Ref: CognitoUserPoolClientName
      GenerateSecret: false          

  UserPoolDomain: 
    Type: AWS::Cognito::UserPoolDomain 
    Properties:
      UserPoolId: !Ref KoandinaUserPool 
      Domain: !Sub  koandina-forecast-${Environment}           
   
Outputs:
  PoolId:
    Description: "Pool Cognito"
    Value:
      Ref: KoandinaUserPool
 
 
