name: CloudFormation

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]    
  pull_request: 
    branches: [ "main" ]    

jobs:
 buckets:
  runs-on: ubuntu-latest
  steps:
    - name: checkout 
      uses: actions/checkout@v3    
    - name: AWS CLI v2
      uses: imehedi/actions-awscli-v2@latest
      with:
          args: s3 ls
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
