name: CloudFormation

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]    
  pull_request: 
    branches: [ "main" ]    

jobs:

  ubuntu_aws_cli:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - CLI_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"     
    name: ubuntu_aws_cli ${{ matrix.CLI_NAME }} ${{ matrix.AWS_CLI_VERSION }}
    steps:
      - name: ubuntu_aws_cli ${{ matrix.CLI_NAME }}
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: ${{ matrix.AWS_CLI_VERSION }}
          rootdir: ${{ matrix.ROOTDIR }}
          workdir: ${{ matrix.WORKDIR }}
      - run: aws s3 ls
        shell: bash
    outputs:
      target_job_status: ${{ job.status }}
