name: CloudFormation

# Controls when the workflow will run
on:
  push:
    branches: [ "develop" ] 
  pull_request: 
    branches: ["develop"]

jobs:

  deploy_aws_auroras:
      runs-on: ubuntu-latest
      environment: develop
      steps:
      - uses: actions/checkout@v3    
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}   
      - name: Deploy Aurora Postgre AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: KoandinaDatabase
          template: master.yaml
          no-fail-on-empty-changeset: "1"     
          parameter-overrides: >-
            NombreAplicacion=Aurora-Forecast, 
            DBMasterUsername=koadmin, 
            Ambiente=${{ secrets.ENVIRONMENT }}, 
            SubnetId2=subnet-087d204dcd7f21a30, 
            AllowedCIDRVPC=172.16.0.0/16, 
            SubnetId1=subnet-0a508be317f6263aa, 
            VpcId=vpc-08977f5f6bbf1d548,
            AllowedCIDRBR=192.168.1.0/27, 
            DBName=forecast, 
            AllowedCIDRCL=192.168.2.0/27,
            ProxyName=rdsproxy-koandina,
            Project=Koandina-Forecast